### ISSUE TITLE
lokinet needs capability's

### ISSUE THREAD

**Issue by unmellow** [unmellow/lokinet-aur#3]
i tried doing setcap that didn't work 
i tried starting it with a service file i got here https://github.com/loki-project/loki-network/blob/debian/buster/debian/lokinet.lokinet.service
it fails everytime 
i have no idea what to do someone help please

**Comment by majestrate** [comment]
what does it fail with?

**Comment by unmellow** [comment]
$sudo start systemctl.service
Job for lokinet.service failed because the control process exited with error code.
$systemctl status lokinet.service
● lokinet.service - LokiNET: Anonymous Network layer thingydoo, client
   Loaded: loaded (/usr/lib/systemd/system/lokinet.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-03-12 11:42:09 EDT; 4s ago
  Process: 28832 ExecStart=/usr/local/bin/lokinet (code=exited, status=203/EXEC)
 Main PID: 28832 (code=exited, status=203/EXEC)
$journelctl -xe
-- 
-- A start job for unit lokinet.service has begun execution.
-- 
-- The job identifier is 357384.
Mar 12 11:45:02 melton-a320ms2h systemd[28915]: lokinet.service: Failed to execute command: No such file or directory
Mar 12 11:45:02 melton-a320ms2h systemd[28915]: lokinet.service: Failed at step EXEC spawning /usr/local/bin/lokinet: No such file or directory
-- Subject: Process /usr/local/bin/lokinet could not be executed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- The process /usr/local/bin/lokinet could not be executed and failed.
-- 
-- The error number returned by this process is ERRNO.
Mar 12 11:45:02 melton-a320ms2h systemd[1]: lokinet.service: Main process exited, code=exited, status=203/EXEC
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- An ExecStart= process belonging to unit lokinet.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 203.
Mar 12 11:45:02 melton-a320ms2h systemd[1]: lokinet.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- The unit lokinet.service has entered the 'failed' state with result 'exit-code'.
Mar 12 11:45:02 melton-a320ms2h systemd[1]: Failed to start LokiNET: Anonymous Network layer thingydoo, client.
-- Subject: A start job for unit lokinet.service has failed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A start job for unit lokinet.service has finished with a failure.
-- 
-- The job identifier is 357384 and the job result is failed.
Mar 12 11:45:02 melton-a320ms2h audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=lokinet comm="systemd" exe="/usr/lib/syst>
Mar 12 11:45:02 melton-a320ms2h kernel: audit: type=1130 audit(1584027902.333:14416): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=lokinet com

**Comment by unmellow** [comment]
lokinet .service is here https://github.com/unmellow/lokinet-aur/blob/master/lokinet.service

**Comment by majestrate** [comment]
`/usr/local/bin/lokinet: No such file or directory` is the error

is it installed to `/usr/bin` or `/usr/local/bin` ?

**Comment by unmellow** [comment]
thanks for pointing that out i fixed it 
now i need to know how to create a user then were golden
i tried using a [loki-network.install](https://github.com/unmellow/lokinet-aur/blob/master/loki-network.install) but it doesn't work and i really don't know why

**Comment by unmellow** [comment]
just learned that i need
install="${pkgname}.install"
in the PKGBUILD closer than ever to getting this done

**Comment by unmellow** [comment]
this issue is solved with my last commit
